# Generated by Django 6.1.1 on 2026-09-13 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('WORKLOAD', 'Workload Distribution'), ('COMPLETION_RATE', 'Task Completion Rate'), ('OVERDUE', 'Overdue Tasks'), ('BURNDOWN', 'Sprint Burndown')], max_length=50)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='JSON payload for report filters (e.g., date ranges, specific users)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='accounts.organization')),
            ],
        ),
    ]
