from locust import HttpUser, task, between

class APIUser(HttpUser):
    wait_time = between(1, 3)
    
    def on_start(self):
        # We assume the user logs in here and gets a JWT token
        response = self.client.post("/api/v1/auth/login/", {
            "email": "loadtest@example.com",
            "password": "password123"
        })
        if response.status_code == 200:
            self.token = response.json().get("access")
            self.client.headers.update({"Authorization": f"Bearer {self.token}"})

    @task(3)
    def get_tasks(self):
        self.client.get("/api/v1/tasks/")

    @task(1)
    def create_task(self):
        self.client.post("/api/v1/tasks/", json={
            "title": "Load Test Task",
            "description": "Generated by Locust",
            "priority": "LOW"
        })

    @task(2)
    def get_analytics(self):
        self.client.get("/api/v1/analytics/dashboard/")
